name: sharpy
channels:
  - conda-forge
  - defaults
dependencies:
  - eigen
  - libopenblas
  - libblas
  - libcblas
  - liblapack
  - libgomp
  - libgfortran
  - libgcc-ng
  - libgfortran-ng
  - python=3.10
