#!/bin/sh
#PBS -lwalltime=08:00:00
#PBS -lselect=1:ncpus=8:mpiprocs=8:mem=16gb

module load anaconda3/personal

cd $HOME/SHARPy_260422/sharpy
source bin/sharpy_vars.sh

source activate sharpy_env_xbeamdev

cd tests/xbeam
python3 generate_minguet_loadramping.py

