case:
    name: r05_sc0p2_newcost
    output_folder: ./output/
base:
    name: base
    route: ./base_case/
    generate_file: generate.py

settings:
    delete_case_folders: false
    cases_folder: ./cases/
    save_data: true

previous_data:
    cases: ../../../../optimisers_postproc/cases/r10_sc0p1_newcost/*.pkl

optimiser:
    numerics:
        tolerance: 0.01
        n_iter: 30
        batch_size: 4
        n_cores: 16
        initial_design_numdata: 4
    parameters:
        0: acceleration
        1: dAoA
        2: ramp_angle
        3: release_velocity
    parameters_initial:
        0: 2.0
        1: 0.1
        2: 0.0
        3: 9.5
    parameters_bounds:
        0: [1.0, 7.0]
        1: [-1.0, 8.0]
        2: [-1.0, 8.0]
        3: [3.0, 15.0]
    cost:
        ground_clearance:
            z_min: -4
            z_0: 2
            scale: 10
        loads:
            reference_loads: 'input/cruise_loads.csv'
            Torsion:
                scale: 0.2
            OOP:
                scale: 0.2
            IP:
                scale: 0.2
    constraints:
        ramp_length: 5.0
        incidence_angle:
            limit: 9.0
            base_aoa: 4.09
