name: SHARPy Tests

on:
  push:
    paths:
      - '*.py'
      - 'lib/*'
      - '.github/workflows/sharpy*'
  pull_request:
    branches:
      - main
      - develop
      - 'rc*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x64
      - name: Pre-Install dependencies
        run: |
          gfortran --version
          export QT_QPA_PLATFORM='offscreen'
          sudo apt install libeigen3-dev
          git submodule init
          git submodule update
          git fetch --tags -f
          mkdir build && cd build
          cmake .. && make install -j 4 && cd ..
          pip install .
          pip install coverage
          coverage run -m unittest discover
          coverage json
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
