name: SHARPy Tests

on:
  push:
    paths:
      - '*.py'
      - 'lib/*'
      - '.github/workflows/sharpy*'
  pull_request:
    branches:
      - main
      - develop
      - 'rc*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.8]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-tags: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x64
      - name: Check that gfortran works
        run: gfortran --version
      - name: Install build package dependencies
        run: sudo apt install libblas-dev liblapack-dev libeigen3-dev
      - name: Install sharpy and coverage using pip
        run: |
          export QT_QPA_PLATFORM='offscreen'
          pip install .
          pip install coverage
      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage json
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
